{% set name = "weathercop" %}
{% set version = "0.1" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # fn: {{ name }}-{{ version }}.tar.gz
  # git_rev: v0.13.1
  # git_url: https://github.com/joerick/pyinstrument.git
  path: weathercop

requirements:
  # host:
  #   # - python >=3.6
  #   - python
  #   # - intelpython
  #   # - setuptools
  #   - pip
  # build:
  host:
    - python >=3.10
    # - intelpython
    - setuptools
    - numpy
    - cython
    - mkl
    - mkl-devel
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # - icc_rt
  run:
    - python >=3.6
    - numpy
    - scipy
    - matplotlib
    - sympy
    - mpmath
    - mkl  [not nomkl]
    - mkl-devel  [not nomkl]
    - cython
    - networkx
    - tqdm
    - future
    - pandas
    # lhglib requirements, delete this, once vg is properly packaged
    - timezonefinder
    - pytables
    - pep8

test:
  imports:
    - weathercop
    # - weathercop.vine
    # - weathercop.multisite
    # - weathercop.copulae

about:
  home: https://fluppenschaechte.mooo.com
  license: BSD
  # license_file: LICENSE

